# Етап 1: Збірка Vue 3 статичних файлів
FROM node:20-alpine AS build
WORKDIR /app

# Забороняємо Puppeteer скачувати Chrome
ENV PUPPETEER_SKIP_DOWNLOAD=true

COPY package*.json ./
RUN npm install

COPY . .
RUN npm run build

# Етап 2: Роздача через Nginx
FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]