apiVersion: v1
kind: Secret
metadata:
  name: app-secret
  namespace: anurieva
type: Opaque
stringData:
  SECRET: "cert-generator-jwt-super-secret-key-2026"
  MONGO_URI: "mongodb://mongodb-service:27017/diploma_db"
